In [6]:
# Basic and plotting packages
suppressMessages( library(kableExtra) )
suppressMessages( library(ggplot2) )
suppressMessages( library(plotly) )
suppressMessages( library(cowplot) )
suppressMessages( library(latex2exp) )
t = theme(plot.title = element_text(size=26, hjust=0.5),
          axis.title = element_text(size=20),
          axis.text = element_text(size=16),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 16),
          plot.subtitle = element_text(size = 18, face="bold"))
theme_set(theme_minimal()+t)
options(repr.plot.width=16, repr.plot.height=6)

suppressMessages( library(gtools) )

# Utils packages
suppressMessages( library(dplyr) ) # Pipeline
suppressMessages( library(snow) ) # Parallel apply, sapply, lapply
suppressMessages( library(pbapply) ) # Progressbar apply, sapply, lapply
suppressMessages( library(pbmcapply) ) # Progress bar in for loop (needs to be installed manually: https://cran.r-project.org/web/packages/pbmcapply/index.html)

suppressMessages( library(TSA) )
suppressMessages( library(rugarch) )

suppressMessages( library(mvtnorm) )
suppressMessages( library(tmvmixnorm) )
suppressMessages( library(truncnorm) )

suppressMessages( library(extRemes) )

suppressMessages( library(VGAM) )

In [90]:
df_scenario1 <- read.csv("scenario1_simulations.csv")
df_scenario2 <- read.csv("scenario2_simulations.csv")
df_scenario3 <- read.csv("scenario3_simulations.csv")

df_scenario1$true_value <- rep(c(0.1,0.1,0.8), 500)
df_scenario1$bias <- df_scenario1$mean - df_scenario1$true_value
df_scenario1$mse <- (df_scenario1$mean - df_scenario1$true_value)**2

df_scenario2$true_value <- rep(c(0.1,0.7,0.2), 500)
df_scenario2$bias <- df_scenario2$mean - df_scenario2$true_value
df_scenario2$mse <- (df_scenario2$mean - df_scenario2$true_value)**2

df_scenario3$true_value <- rep(c(0.1,0.3,0.3), 500)
df_scenario3$bias <- df_scenario3$mean - df_scenario3$true_value
df_scenario3$mse <- (df_scenario3$mean - df_scenario3$true_value)**2

head(df_scenario1)
head(df_scenario2)
head(df_scenario3)

  T   replica parameter mean      median    sd         X2.5.      X25.
1 500 1       alpha0    0.1866283 0.1407177 0.14337896 0.04847414 0.08864359
2 500 1       alpha1    0.1310606 0.1225209 0.05561969 0.04539158 0.09064521
3 500 1       beta1     0.6957031 0.7429838 0.16963073 0.16999130 0.60679324
4 500 2       alpha0    0.1473960 0.1376194 0.05957224 0.05903406 0.11007166
5 500 2       alpha1    0.1571828 0.1497073 0.05100975 0.07802267 0.11915950
6 500 2       beta1     0.6747172 0.6852565 0.09408859 0.44915810 0.62721957
  X50.      X75.      X97.5.    true_value bias        mse
1 0.1407177 0.2431742 0.6790003 0.1         0.08662825 0.0075044544
2 0.1225209 0.1638474 0.2646224 0.1         0.03106062 0.0009647624
3 0.7429838 0.8200887 0.8933367 0.8        -0.10429693 0.0108778495
4 0.1376194 0.1741890 0.2913512 0.1         0.04739604 0.0022463846
5 0.1497073 0.1884195 0.2723856 0.1         0.05718280 0.0032698731
6 0.6852565 0.7347058 0.8282631 0.8        -0.12528279 0.0156957787

  T   replica parameter mean       median     sd         X2.5.      X25.
1 500 1       alpha0    0.12336849 0.12151435 0.02914560 0.07807545 0.10688108
2 500 1       alpha1    0.76208916 0.76837058 0.09317368 0.56792993 0.71047953
3 500 1       beta1     0.13240312 0.13064156 0.06411410 0.02143231 0.08211352
4 500 2       alpha0    0.08795682 0.08600361 0.02318763 0.06098615 0.07622666
5 500 2       alpha1    0.68791381 0.68913741 0.08711209 0.51603470 0.63020466
6 500 2       beta1     0.20737987 0.20827209 0.06038274 0.09949057 0.16266721
  X50.       X75.       X97.5.    true_value bias         mse
1 0.12151435 0.13807553 0.1679076 0.1         0.023368489 5.460863e-04
2 0.76837058 0.82615525 0.9127933 0.7         0.062089156 3.855063e-03
3 0.13064156 0.17575790 0.2627942 0.2        -0.067596883 4.569339e-03
4 0.08600361 0.09674609 0.1207054 0.1        -0.012043184 1.450383e-04
5 0.68913741 0.75137593 0.8482704 0.7        -0.012086187 1.460759e-04
6 0.20827209 0.24836240 0.3278347 0.2         0.007379874 5.446254e-05

  T   replica parameter mean       median     sd         X2.5.      X25.
1 500 1       alpha0    0.11751588 0.11456096 0.03394400 0.06027425 0.09595998
2 500 1       alpha1    0.36520302 0.36001977 0.08828324 0.20355178 0.30353358
3 500 1       beta1     0.21811302 0.21855154 0.12718815 0.01447762 0.11258134
4 500 2       alpha0    0.07787403 0.07322034 0.02801752 0.04093511 0.06162060
5 500 2       alpha1    0.38876267 0.37972266 0.09111396 0.23750347 0.32250849
6 500 2       beta1     0.30478903 0.31653744 0.12839398 0.02856280 0.22341149
  X50.       X75.       X97.5.    true_value bias        mse
1 0.11456096 0.13793016 0.1724737 0.1         0.01751588 3.068059e-04
2 0.36001977 0.42161176 0.5581533 0.3         0.06520302 4.251434e-03
3 0.21855154 0.30582968 0.4869336 0.3        -0.08188698 6.705478e-03
4 0.07322034 0.08851221 0.1329135 0.1        -0.02212597 4.895584e-04
5 0.37972266 0.44680297 0.5926585 0.3         0.08876267 7.878811e-03
6 0.31653744 0.39828700 0.5296038 0.3         0.00478903 2.293481e-05

### Scenario 1: $\alpha_0 = 0.1$, $\alpha_1 = 0.1$, $\beta_1 = 0.8$

In [80]:
# Scenario 1
true_alpha0 <- 0.1
true_alpha1 <- 0.1
true_beta1 <- 0.8

alpha0_lower_500 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 500), 7]
alpha0_upper_500 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 500), 11]
alpha0_lower_750 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 750), 7]
alpha0_upper_750 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 750), 11]
alpha0_lower_1000 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 1000), 7]
alpha0_upper_1000 <- df_scenario1[ (df_scenario1$parameter == "alpha0") & (df_scenario1$T == 1000), 11]
coverage_prob_alpha0_500 <- mean( (alpha0_lower_500 < true_alpha0) & (alpha0_upper_500 > true_alpha0) )
coverage_prob_alpha0_750 <- mean( (alpha0_lower_750 < true_alpha0) & (alpha0_upper_750 > true_alpha0) )
coverage_prob_alpha0_1000 <- mean( (alpha0_lower_1000 < true_alpha0) & (alpha0_upper_1000 > true_alpha0) )

alpha1_lower_500 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 500), 7]
alpha1_upper_500 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 500), 11]
alpha1_lower_750 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 750), 7]
alpha1_upper_750 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 750), 11]
alpha1_lower_1000 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 1000), 7]
alpha1_upper_1000 <- df_scenario1[ (df_scenario1$parameter == "alpha1") & (df_scenario1$T == 1000), 11]
coverage_prob_alpha1_500 <- mean( (alpha1_lower_500 < true_alpha1) & (alpha1_upper_500 > true_alpha1) )
coverage_prob_alpha1_750 <- mean( (alpha1_lower_750 < true_alpha1) & (alpha1_upper_750 > true_alpha1) )
coverage_prob_alpha1_1000 <- mean( (alpha1_lower_1000 < true_alpha1) & (alpha1_upper_1000 > true_alpha1) )

beta1_lower_500 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 500), 7]
beta1_upper_500 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 500), 11]
beta1_lower_750 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 750), 7]
beta1_upper_750 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 750), 11]
beta1_lower_1000 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 1000), 7]
beta1_upper_1000 <- df_scenario1[ (df_scenario1$parameter == "beta1") & (df_scenario1$T == 1000), 11]
coverage_prob_beta1_500 <- mean( (beta1_lower_500 < true_beta1) & (beta1_upper_500 > true_beta1) )
coverage_prob_beta1_750 <- mean( (beta1_lower_750 < true_beta1) & (beta1_upper_750 > true_beta1) )
coverage_prob_beta1_1000 <- mean( (beta1_lower_1000 < true_beta1) & (beta1_upper_1000 > true_beta1) )

In [94]:
summary_scenario1 <- df_scenario1 %>% group_by(parameter, T) %>% summarise(
    true_value = first(true_value),
    bias = mean(bias, na.rm = TRUE),
    rmse = sqrt( mean(mse, na.rm = TRUE) ),
    X2.5. = mean(`X2.5.`, na.rm = TRUE),
    X25. = mean(`X25.`, na.rm = TRUE),
    X50. = mean(`X50.`, na.rm = TRUE),
    X75. = mean(`X75.`, na.rm = TRUE),
    X97.5. = mean(`X97.5.`, na.rm = TRUE),
    .groups = "drop"
)
summary_scenario1$coverage_prob <- c(
    coverage_prob_alpha0_500,
    coverage_prob_alpha0_750,
    coverage_prob_alpha0_1000,
    coverage_prob_alpha1_500,
    coverage_prob_alpha1_750,
    coverage_prob_alpha1_1000,
    coverage_prob_beta1_500,
    coverage_prob_beta1_750,
    coverage_prob_beta1_1000
)
summary_scenario1 <- summary_scenario1 %>% mutate(
    interval = paste0( "(", round(`X2.5.`, 2), ", ", round(`X97.5.`, 2), ")" )
)
summary_scenario1

  parameter T    true_value bias        rmse       X2.5.      X25.
1 alpha0     500 0.1         0.11077317 0.14990993 0.06882133 0.12789373
2 alpha0     750 0.1         0.06985680 0.10769056 0.06300680 0.10879957
3 alpha0    1000 0.1         0.04551226 0.08424057 0.06107221 0.09948150
4 alpha1     500 0.1         0.02661272 0.04859810 0.05082070 0.09250674
5 alpha1     750 0.1         0.01887454 0.03697107 0.05764872 0.09233967
6 alpha1    1000 0.1         0.01455578 0.03116593 0.06227314 0.09230883
7 beta1      500 0.8        -0.14155441 0.18300518 0.33186382 0.58117282
8 beta1      750 0.8        -0.09069432 0.13194719 0.43381568 0.65560506
9 beta1     1000 0.8        -0.06025875 0.10114516 0.51328549 0.69975034
  X50.      X75.      X97.5.    coverage_prob interval
1 0.1852647 0.2677523 0.4938490 0.854         (0.07, 0.49)
2 0.1492762 0.2080162 0.4015798 0.884         (0.06, 0.4)
3 0.1306593 0.1730908 0.3311319 0.930         (0.06, 0.33)
4 0.1207938 0.1542367 0.2361380 0.948         (0.05, 0.24)
5 0.1148071 0.1406854 0.2034715 0.942         (0.06, 0.2)
6 0.1114235 0.1329670 0.1850486 0.956         (0.06, 0.19)
7 0.6829633 0.7601659 0.8518135 0.842         (0.33, 0.85)
8 0.7306577 0.7863037 0.8576915 0.908         (0.43, 0.86)
9 0.7553968 0.7993387 0.8592388 0.916         (0.51, 0.86)

In [100]:
kbl(summary_scenario1[,c("parameter", "true_value", "T", "bias", "rmse", "interval", "coverage_prob")], format = "latex", booktabs = TRUE, digits = 4)

\begin{tabular}[t]{lrrrrlr}
\toprule
parameter & true\_value & T & bias & rmse & interval & coverage\_prob\\
\midrule
alpha0 & 0.1 & 500 & 0.1108 & 0.1499 & (0.07, 0.49) & 0.854\\
alpha0 & 0.1 & 750 & 0.0699 & 0.1077 & (0.06, 0.4) & 0.884\\
alpha0 & 0.1 & 1000 & 0.0455 & 0.0842 & (0.06, 0.33) & 0.930\\
alpha1 & 0.1 & 500 & 0.0266 & 0.0486 & (0.05, 0.24) & 0.948\\
alpha1 & 0.1 & 750 & 0.0189 & 0.0370 & (0.06, 0.2) & 0.942\\
\addlinespace
alpha1 & 0.1 & 1000 & 0.0146 & 0.0312 & (0.06, 0.19) & 0.956\\
beta1 & 0.8 & 500 & -0.1416 & 0.1830 & (0.33, 0.85) & 0.842\\
beta1 & 0.8 & 750 & -0.0907 & 0.1319 & (0.43, 0.86) & 0.908\\
beta1 & 0.8 & 1000 & -0.0603 & 0.1011 & (0.51, 0.86) & 0.916\\
\bottomrule
\end{tabular}

### Scenario 2: $\alpha_0 = 0.1$, $\alpha_1 = 0.7$, $\beta_1 = 0.2$

In [111]:
# Scenario 2
true_alpha0 <- 0.1
true_alpha1 <- 0.7
true_beta1 <- 0.2

alpha0_lower_500 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 500), 7]
alpha0_upper_500 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 500), 11]
alpha0_lower_750 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 750), 7]
alpha0_upper_750 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 750), 11]
alpha0_lower_1000 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 1000), 7]
alpha0_upper_1000 <- df_scenario2[ (df_scenario2$parameter == "alpha0") & (df_scenario2$T == 1000), 11]
coverage_prob_alpha0_500 <- mean( (alpha0_lower_500 < true_alpha0) & (alpha0_upper_500 > true_alpha0) )
coverage_prob_alpha0_750 <- mean( (alpha0_lower_750 < true_alpha0) & (alpha0_upper_750 > true_alpha0) )
coverage_prob_alpha0_1000 <- mean( (alpha0_lower_1000 < true_alpha0) & (alpha0_upper_1000 > true_alpha0) )

alpha1_lower_500 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 500), 7]
alpha1_upper_500 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 500), 11]
alpha1_lower_750 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 750), 7]
alpha1_upper_750 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 750), 11]
alpha1_lower_1000 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 1000), 7]
alpha1_upper_1000 <- df_scenario2[ (df_scenario2$parameter == "alpha1") & (df_scenario2$T == 1000), 11]
coverage_prob_alpha1_500 <- mean( (alpha1_lower_500 < true_alpha1) & (alpha1_upper_500 > true_alpha1) )
coverage_prob_alpha1_750 <- mean( (alpha1_lower_750 < true_alpha1) & (alpha1_upper_750 > true_alpha1) )
coverage_prob_alpha1_1000 <- mean( (alpha1_lower_1000 < true_alpha1) & (alpha1_upper_1000 > true_alpha1) )

beta1_lower_500 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 500), 7]
beta1_upper_500 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 500), 11]
beta1_lower_750 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 750), 7]
beta1_upper_750 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 750), 11]
beta1_lower_1000 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 1000), 7]
beta1_upper_1000 <- df_scenario2[ (df_scenario2$parameter == "beta1") & (df_scenario2$T == 1000), 11]
coverage_prob_beta1_500 <- mean( (beta1_lower_500 < true_beta1) & (beta1_upper_500 > true_beta1) )
coverage_prob_beta1_750 <- mean( (beta1_lower_750 < true_beta1) & (beta1_upper_750 > true_beta1) )
coverage_prob_beta1_1000 <- mean( (beta1_lower_1000 < true_beta1) & (beta1_upper_1000 > true_beta1) )

In [112]:
summary_scenario2 <- df_scenario2 %>% group_by(parameter, T) %>% summarise(
    true_value = first(true_value),
    bias = mean(bias, na.rm = TRUE),
    rmse = sqrt( mean(mse, na.rm = TRUE) ),
    X2.5. = mean(`X2.5.`, na.rm = TRUE),
    X25. = mean(`X25.`, na.rm = TRUE),
    X50. = mean(`X50.`, na.rm = TRUE),
    X75. = mean(`X75.`, na.rm = TRUE),
    X97.5. = mean(`X97.5.`, na.rm = TRUE),
    .groups = "drop"
)
summary_scenario2$coverage_prob <- c(
    coverage_prob_alpha0_500,
    coverage_prob_alpha0_750,
    coverage_prob_alpha0_1000,
    coverage_prob_alpha1_500,
    coverage_prob_alpha1_750,
    coverage_prob_alpha1_1000,
    coverage_prob_beta1_500,
    coverage_prob_beta1_750,
    coverage_prob_beta1_1000
)
summary_scenario2 <- summary_scenario2 %>% mutate(
    interval = paste0( "(", round(`X2.5.`, 2), ", ", round(`X97.5.`, 2), ")" )
)
summary_scenario2

  parameter T    true_value bias          rmse       X2.5.      X25.
1 alpha0     500 0.1         0.0069604928 0.01842239 0.07030588 0.09285285
2 alpha0     750 0.1         0.0057761169 0.01629211 0.07513307 0.09417990
3 alpha0    1000 0.1         0.0045254030 0.01385680 0.07703900 0.09426556
4 alpha1     500 0.7        -0.0374385930 0.08348596 0.49332580 0.60716975
5 alpha1     750 0.7        -0.0257169986 0.07054651 0.52895936 0.62725340
6 alpha1    1000 0.7        -0.0247808809 0.06588062 0.54553499 0.63354429
7 beta1      500 0.2        -0.0004250845 0.05632548 0.09299950 0.15575964
8 beta1      750 0.2        -0.0024256275 0.04984835 0.10909216 0.16225053
9 beta1     1000 0.2         0.0021090570 0.04421667 0.12250186 0.17097080
  X50.      X75.      X97.5.    coverage_prob interval
1 0.1055186 0.1182922 0.1451798 0.966         (0.07, 0.15)
2 0.1045507 0.1147996 0.1360019 0.948         (0.08, 0.14)
3 0.1033970 0.1123158 0.1307157 0.952         (0.08, 0.13)
4 0.6648376 0.7218285 0.8191625 0.964         (0.49, 0.82)
5 0.6768681 0.7251013 0.8096244 0.960         (0.53, 0.81)
6 0.6776136 0.7205633 0.7966133 0.946         (0.55, 0.8)
7 0.1948724 0.2386779 0.3317558 0.968         (0.09, 0.33)
8 0.1941743 0.2294437 0.3047178 0.950         (0.11, 0.3)
9 0.1993577 0.2305430 0.2966105 0.954         (0.12, 0.3)

In [114]:
kbl(summary_scenario2[,c("parameter", "true_value", "T", "bias", "rmse", "interval", "coverage_prob")], format = "latex", booktabs = TRUE, digits = 4)

\begin{tabular}[t]{lrrrrlr}
\toprule
parameter & true\_value & T & bias & rmse & interval & coverage\_prob\\
\midrule
alpha0 & 0.1 & 500 & 0.0070 & 0.0184 & (0.07, 0.15) & 0.966\\
alpha0 & 0.1 & 750 & 0.0058 & 0.0163 & (0.08, 0.14) & 0.948\\
alpha0 & 0.1 & 1000 & 0.0045 & 0.0139 & (0.08, 0.13) & 0.952\\
alpha1 & 0.7 & 500 & -0.0374 & 0.0835 & (0.49, 0.82) & 0.964\\
alpha1 & 0.7 & 750 & -0.0257 & 0.0705 & (0.53, 0.81) & 0.960\\
\addlinespace
alpha1 & 0.7 & 1000 & -0.0248 & 0.0659 & (0.55, 0.8) & 0.946\\
beta1 & 0.2 & 500 & -0.0004 & 0.0563 & (0.09, 0.33) & 0.968\\
beta1 & 0.2 & 750 & -0.0024 & 0.0498 & (0.11, 0.3) & 0.950\\
beta1 & 0.2 & 1000 & 0.0021 & 0.0442 & (0.12, 0.3) & 0.954\\
\bottomrule
\end{tabular}

### Scenario 3: $\alpha_0 = 0.1$, $\alpha_1 = 0.3$, $\beta_1 = 0.3$

In [115]:
# Scenario 2
true_alpha0 <- 0.1
true_alpha1 <- 0.3
true_beta1 <- 0.3

alpha0_lower_500 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 500), 7]
alpha0_upper_500 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 500), 11]
alpha0_lower_750 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 750), 7]
alpha0_upper_750 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 750), 11]
alpha0_lower_1000 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 1000), 7]
alpha0_upper_1000 <- df_scenario3[ (df_scenario3$parameter == "alpha0") & (df_scenario3$T == 1000), 11]
coverage_prob_alpha0_500 <- mean( (alpha0_lower_500 < true_alpha0) & (alpha0_upper_500 > true_alpha0) )
coverage_prob_alpha0_750 <- mean( (alpha0_lower_750 < true_alpha0) & (alpha0_upper_750 > true_alpha0) )
coverage_prob_alpha0_1000 <- mean( (alpha0_lower_1000 < true_alpha0) & (alpha0_upper_1000 > true_alpha0) )

alpha1_lower_500 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 500), 7]
alpha1_upper_500 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 500), 11]
alpha1_lower_750 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 750), 7]
alpha1_upper_750 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 750), 11]
alpha1_lower_1000 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 1000), 7]
alpha1_upper_1000 <- df_scenario3[ (df_scenario3$parameter == "alpha1") & (df_scenario3$T == 1000), 11]
coverage_prob_alpha1_500 <- mean( (alpha1_lower_500 < true_alpha1) & (alpha1_upper_500 > true_alpha1) )
coverage_prob_alpha1_750 <- mean( (alpha1_lower_750 < true_alpha1) & (alpha1_upper_750 > true_alpha1) )
coverage_prob_alpha1_1000 <- mean( (alpha1_lower_1000 < true_alpha1) & (alpha1_upper_1000 > true_alpha1) )

beta1_lower_500 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 500), 7]
beta1_upper_500 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 500), 11]
beta1_lower_750 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 750), 7]
beta1_upper_750 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 750), 11]
beta1_lower_1000 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 1000), 7]
beta1_upper_1000 <- df_scenario3[ (df_scenario3$parameter == "beta1") & (df_scenario3$T == 1000), 11]
coverage_prob_beta1_500 <- mean( (beta1_lower_500 < true_beta1) & (beta1_upper_500 > true_beta1) )
coverage_prob_beta1_750 <- mean( (beta1_lower_750 < true_beta1) & (beta1_upper_750 > true_beta1) )
coverage_prob_beta1_1000 <- mean( (beta1_lower_1000 < true_beta1) & (beta1_upper_1000 > true_beta1) )

In [116]:
summary_scenario3 <- df_scenario3 %>% group_by(parameter, T) %>% summarise(
    true_value = first(true_value),
    bias = mean(bias, na.rm = TRUE),
    rmse = sqrt( mean(mse, na.rm = TRUE) ),
    X2.5. = mean(`X2.5.`, na.rm = TRUE),
    X25. = mean(`X25.`, na.rm = TRUE),
    X50. = mean(`X50.`, na.rm = TRUE),
    X75. = mean(`X75.`, na.rm = TRUE),
    X97.5. = mean(`X97.5.`, na.rm = TRUE),
    .groups = "drop"
)
summary_scenario3$coverage_prob <- c(
    coverage_prob_alpha0_500,
    coverage_prob_alpha0_750,
    coverage_prob_alpha0_1000,
    coverage_prob_alpha1_500,
    coverage_prob_alpha1_750,
    coverage_prob_alpha1_1000,
    coverage_prob_beta1_500,
    coverage_prob_beta1_750,
    coverage_prob_beta1_1000
)
summary_scenario3 <- summary_scenario3 %>% mutate(
    interval = paste0( "(", round(`X2.5.`, 2), ", ", round(`X97.5.`, 2), ")" )
)
summary_scenario3

  parameter T    true_value bias         rmse       X2.5.      X25.
1 alpha0     500 0.1         0.006307575 0.02180672 0.05950817 0.08786440
2 alpha0     750 0.1         0.007319050 0.02017324 0.06560756 0.09138862
3 alpha0    1000 0.1         0.004209163 0.01911388 0.06695526 0.08970338
4 alpha1     500 0.3         0.009902428 0.07101220 0.17728193 0.25656999
5 alpha1     750 0.3         0.006199263 0.05966617 0.19620358 0.26314987
6 alpha1    1000 0.3         0.004785471 0.05278582 0.20761646 0.26743493
7 beta1      500 0.3        -0.022490576 0.09772669 0.07406421 0.19329452
8 beta1      750 0.3        -0.025959829 0.09335385 0.09009738 0.20137921
9 beta1     1000 0.3        -0.013415841 0.09096096 0.11287294 0.22175031
  X50.      X75.      X97.5.    coverage_prob interval
1 0.1045779 0.1219134 0.1569380 0.982         (0.06, 0.16)
2 0.1059306 0.1207701 0.1510737 0.978         (0.07, 0.15)
3 0.1026742 0.1159198 0.1440576 0.954         (0.07, 0.14)
4 0.3045551 0.3574723 0.4728014 0.958         (0.18, 0.47)
5 0.3026528 0.3453973 0.4366877 0.954         (0.2, 0.44)
6 0.3019548 0.3390920 0.4180828 0.956         (0.21, 0.42)
7 0.2715169 0.3551412 0.5166713 0.974         (0.07, 0.52)
8 0.2693518 0.3417462 0.4843629 0.976         (0.09, 0.48)
9 0.2838620 0.3486487 0.4742674 0.952         (0.11, 0.47)

In [117]:
kbl(summary_scenario3[,c("parameter", "true_value", "T", "bias", "rmse", "interval", "coverage_prob")], format = "latex", booktabs = TRUE, digits = 4)

\begin{tabular}[t]{lrrrrlr}
\toprule
parameter & true\_value & T & bias & rmse & interval & coverage\_prob\\
\midrule
alpha0 & 0.1 & 500 & 0.0063 & 0.0218 & (0.06, 0.16) & 0.982\\
alpha0 & 0.1 & 750 & 0.0073 & 0.0202 & (0.07, 0.15) & 0.978\\
alpha0 & 0.1 & 1000 & 0.0042 & 0.0191 & (0.07, 0.14) & 0.954\\
alpha1 & 0.3 & 500 & 0.0099 & 0.0710 & (0.18, 0.47) & 0.958\\
alpha1 & 0.3 & 750 & 0.0062 & 0.0597 & (0.2, 0.44) & 0.954\\
\addlinespace
alpha1 & 0.3 & 1000 & 0.0048 & 0.0528 & (0.21, 0.42) & 0.956\\
beta1 & 0.3 & 500 & -0.0225 & 0.0977 & (0.07, 0.52) & 0.974\\
beta1 & 0.3 & 750 & -0.0260 & 0.0934 & (0.09, 0.48) & 0.976\\
beta1 & 0.3 & 1000 & -0.0134 & 0.0910 & (0.11, 0.47) & 0.952\\
\bottomrule
\end{tabular}